server.port=${PORT:8080}
spring.application.name=appWebsocket

# ===============================
# CONEXION A AWS RDS (MAESTRO)
# ===============================
spring.datasource.url=jdbc:mysql://logistica-master.cnq2g48o2enl.us-east-2.rds.amazonaws.com:3306/db_logistica?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=admin
spring.datasource.password=chasquiexpress
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# HIKARI POOL CONFIGURACION OPTIMIZADA (ANTI-CRASH)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# ===============================
# CONFIGURACION DE JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
